name: 'First interaction'
description: 'Greet new contributors when they create their first issue or open their first pull request'
author: 'GitHub'
inputs:
  repo-token:
    description: 'Token for the repository. Can be passed in using {{ secrets.GITHUB_TOKEN }}'
    required: true
  issue-message: '👋 Hey, thank you for your first issue\nMake sure to check our [bug](https://github.com/FnrDev/slash-commands/blob/main/.github/ISSUE_TEMPLATE/bug_report.md) or [feature request](https://github.com/FnrDev/slash-commands/blob/main/.github/ISSUE_TEMPLATE/feature_request.md) template to aviod closing this issue.'
  pr-message: '👋 Hey, thank you for your first contributing\nMake sure to check our [contributing](https://github.com/FnrDev/slash-commands/blob/main/.github/CONTRIBUTING.md) guide to aviod closing this PR.'
runs:
  using: 'docker'
  image: 'Dockerfile'